// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceMarketplace.Data;

#nullable disable

namespace ServiceMarketplace.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ServiceMarketplace.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessID")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Cost")
                        .HasColumnType("REAL");

                    b.Property<string>("CustomerID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusinessID = 1,
                            Cost = 100f,
                            CustomerID = "b01873ec-546c-4813-b93b-e7bef86a4de4",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            EndTime = new DateTime(2024, 8, 2, 20, 14, 10, 529, DateTimeKind.Local).AddTicks(6843),
                            ServiceId = 1,
                            StartTime = new DateTime(2024, 8, 2, 19, 14, 10, 529, DateTimeKind.Local).AddTicks(6798),
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            BusinessID = 2,
                            Cost = 150f,
                            CustomerID = "06874549-8158-4144-891c-1a33141904bd",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            EndTime = new DateTime(2024, 8, 3, 20, 14, 10, 529, DateTimeKind.Local).AddTicks(6849),
                            ServiceId = 2,
                            StartTime = new DateTime(2024, 8, 3, 19, 14, 10, 529, DateTimeKind.Local).AddTicks(6847),
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            BusinessID = 3,
                            Cost = 200f,
                            CustomerID = "b01873ec-546c-4813-b93b-e7bef86a4de4",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            EndTime = new DateTime(2024, 8, 4, 20, 14, 10, 529, DateTimeKind.Local).AddTicks(6853),
                            ServiceId = 3,
                            StartTime = new DateTime(2024, 8, 4, 19, 14, 10, 529, DateTimeKind.Local).AddTicks(6852),
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            BusinessID = 4,
                            Cost = 250f,
                            CustomerID = "06874549-8158-4144-891c-1a33141904bd",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            EndTime = new DateTime(2024, 8, 5, 20, 14, 10, 529, DateTimeKind.Local).AddTicks(6858),
                            ServiceId = 4,
                            StartTime = new DateTime(2024, 8, 5, 19, 14, 10, 529, DateTimeKind.Local).AddTicks(6857),
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            BusinessID = 5,
                            Cost = 300f,
                            CustomerID = "06874549-8158-4144-891c-1a33141904bd",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            EndTime = new DateTime(2024, 8, 6, 20, 14, 10, 529, DateTimeKind.Local).AddTicks(6862),
                            ServiceId = 5,
                            StartTime = new DateTime(2024, 8, 6, 19, 14, 10, 529, DateTimeKind.Local).AddTicks(6861),
                            Status = 1
                        });
                });

            modelBuilder.Entity("ServiceMarketplace.Entities.Business", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description for Business 1",
                            Name = "Business 1",
                            PhoneNumber = "5555555551"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description for Business 2",
                            Name = "Business 2",
                            PhoneNumber = "5555555552"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description for Business 3",
                            Name = "Business 3",
                            PhoneNumber = "5555555553"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description for Business 4",
                            Name = "Business 4",
                            PhoneNumber = "5555555554"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description for Business 5",
                            Name = "Business 5",
                            PhoneNumber = "5555555555"
                        });
                });

            modelBuilder.Entity("ServiceMarketplace.Entities.BusinessUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BusinessUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAdmin = true,
                            UserId = ""
                        },
                        new
                        {
                            Id = 2,
                            IsAdmin = false,
                            UserId = ""
                        },
                        new
                        {
                            Id = 3,
                            IsAdmin = true,
                            UserId = ""
                        },
                        new
                        {
                            Id = 4,
                            IsAdmin = false,
                            UserId = ""
                        },
                        new
                        {
                            Id = 5,
                            IsAdmin = true,
                            UserId = ""
                        },
                        new
                        {
                            Id = 6,
                            IsAdmin = false,
                            UserId = ""
                        },
                        new
                        {
                            Id = 7,
                            IsAdmin = true,
                            UserId = ""
                        },
                        new
                        {
                            Id = 8,
                            IsAdmin = false,
                            UserId = ""
                        },
                        new
                        {
                            Id = 9,
                            IsAdmin = true,
                            UserId = ""
                        },
                        new
                        {
                            Id = 10,
                            IsAdmin = false,
                            UserId = ""
                        });
                });

            modelBuilder.Entity("ServiceMarketplace.Entities.Inquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentInquiriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inquiries");
                });

            modelBuilder.Entity("ServiceMarketplace.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentReviewId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ServiceMarketplace.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusinessId = 1,
                            Description = "Description for Service 1",
                            Duration = new TimeSpan(0, 0, 30, 0, 0),
                            Price = 50.0,
                            Rating = 1.0,
                            ServiceName = "Service 1"
                        },
                        new
                        {
                            Id = 2,
                            BusinessId = 2,
                            Description = "Description for Service 2",
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            Price = 60.0,
                            Rating = 2.0,
                            ServiceName = "Service 2"
                        },
                        new
                        {
                            Id = 3,
                            BusinessId = 3,
                            Description = "Description for Service 3",
                            Duration = new TimeSpan(0, 0, 30, 0, 0),
                            Price = 70.0,
                            Rating = 3.0,
                            ServiceName = "Service 3"
                        },
                        new
                        {
                            Id = 4,
                            BusinessId = 4,
                            Description = "Description for Service 4",
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            Price = 80.0,
                            Rating = 4.0,
                            ServiceName = "Service 4"
                        },
                        new
                        {
                            Id = 5,
                            BusinessId = 5,
                            Description = "Description for Service 5",
                            Duration = new TimeSpan(0, 1, 30, 0, 0),
                            Price = 90.0,
                            Rating = 5.0,
                            ServiceName = "Service 5"
                        });
                });

            modelBuilder.Entity("ServiceMarketplace.Entities.ServiceAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DaysAvailable")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServiceAvailability");
                });

            modelBuilder.Entity("ServiceMarketplace.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            AccountType = 0,
                            Address = "",
                            City = "",
                            ConcurrencyStamp = "871170d6-6f35-4a1b-9441-a9eda6f82e83",
                            Email = "customer1@yahoo.com",
                            EmailConfirmed = false,
                            FirstName = "Customer",
                            LastName = "One",
                            LockoutEnabled = false,
                            PhoneNumber = "5555555555",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "51be67de-1b3d-458f-8892-a1aa6072bf90",
                            State = "",
                            TwoFactorEnabled = false,
                            ZipCode = ""
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            AccountType = 0,
                            Address = "",
                            City = "",
                            ConcurrencyStamp = "f7381f47-9ab1-4354-a59d-12061ca33645",
                            Email = "customer2@yahoo.com",
                            EmailConfirmed = false,
                            FirstName = "Customer",
                            LastName = "Two",
                            LockoutEnabled = false,
                            PhoneNumber = "5555555555",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "13be536a-808f-46c5-a219-950523f349a8",
                            State = "",
                            TwoFactorEnabled = false,
                            ZipCode = ""
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            AccountType = 0,
                            Address = "",
                            City = "",
                            ConcurrencyStamp = "34c21988-2728-4458-a71a-8b76e3a43b49",
                            Email = "customer3@yahoo.com",
                            EmailConfirmed = false,
                            FirstName = "Customer",
                            LastName = "Three",
                            LockoutEnabled = false,
                            PhoneNumber = "5555555555",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8abb6f13-9a95-4190-bd24-b446524838e8",
                            State = "",
                            TwoFactorEnabled = false,
                            ZipCode = ""
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            AccountType = 0,
                            Address = "",
                            City = "",
                            ConcurrencyStamp = "1a6c79ca-5a61-4122-82f7-7d1e6e2bc6f7",
                            Email = "customer4@yahoo.com",
                            EmailConfirmed = false,
                            FirstName = "Customer",
                            LastName = "Four",
                            LockoutEnabled = false,
                            PhoneNumber = "5555555555",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "24b34e3f-9d7a-43ef-9cd6-66fe8146e072",
                            State = "",
                            TwoFactorEnabled = false,
                            ZipCode = ""
                        },
                        new
                        {
                            Id = "5",
                            AccessFailedCount = 0,
                            AccountType = 0,
                            Address = "",
                            City = "",
                            ConcurrencyStamp = "b32852ed-0831-4889-82d4-51bf811c18b3",
                            Email = "customer5@yahoo.com",
                            EmailConfirmed = false,
                            FirstName = "Customer",
                            LastName = "Five",
                            LockoutEnabled = false,
                            PhoneNumber = "5555555555",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c36a5c7b-3437-4296-bfe9-56ebd9b4ca12",
                            State = "",
                            TwoFactorEnabled = false,
                            ZipCode = ""
                        });
                });

            modelBuilder.Entity("ServiceMarketplace.Entities.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2023, 6, 1),
                            Summary = "Freezing",
                            TemperatureC = -5
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2023, 6, 2),
                            Summary = "Bracing",
                            TemperatureC = 0
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2023, 6, 3),
                            Summary = "Chilly",
                            TemperatureC = 5
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2023, 6, 4),
                            Summary = "Cool",
                            TemperatureC = 10
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2023, 6, 5),
                            Summary = "Mild",
                            TemperatureC = 15
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateOnly(2023, 6, 6),
                            Summary = "Warm",
                            TemperatureC = 20
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateOnly(2023, 6, 7),
                            Summary = "Balmy",
                            TemperatureC = 25
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateOnly(2023, 6, 8),
                            Summary = "Hot",
                            TemperatureC = 30
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateOnly(2023, 6, 9),
                            Summary = "Sweltering",
                            TemperatureC = 35
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateOnly(2023, 6, 10),
                            Summary = "Scorching",
                            TemperatureC = 40
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ServiceMarketplace.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ServiceMarketplace.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceMarketplace.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ServiceMarketplace.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServiceMarketplace.Entities.Business", b =>
                {
                    b.OwnsOne("ServiceMarketplace.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<int>("BusinessId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Coordinate")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Zipcode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("BusinessId");

                            b1.ToTable("Businesses");

                            b1.WithOwner()
                                .HasForeignKey("BusinessId");

                            b1.HasData(
                                new
                                {
                                    BusinessId = 1,
                                    City = "City 1",
                                    Coordinate = "",
                                    State = "State 1",
                                    Street = "Street 1",
                                    Zipcode = "Zip1"
                                },
                                new
                                {
                                    BusinessId = 2,
                                    City = "City 2",
                                    Coordinate = "",
                                    State = "State 2",
                                    Street = "Street 2",
                                    Zipcode = "Zip2"
                                },
                                new
                                {
                                    BusinessId = 3,
                                    City = "City 3",
                                    Coordinate = "",
                                    State = "State 3",
                                    Street = "Street 3",
                                    Zipcode = "Zip3"
                                },
                                new
                                {
                                    BusinessId = 4,
                                    City = "City 4",
                                    Coordinate = "",
                                    State = "State 4",
                                    Street = "Street 4",
                                    Zipcode = "Zip4"
                                },
                                new
                                {
                                    BusinessId = 5,
                                    City = "City 5",
                                    Coordinate = "",
                                    State = "State 5",
                                    Street = "Street 5",
                                    Zipcode = "Zip5"
                                });
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("ServiceMarketplace.Entities.Review", b =>
                {
                    b.HasOne("ServiceMarketplace.Entities.Service", null)
                        .WithMany("Reviews")
                        .HasForeignKey("ServiceId");
                });

            modelBuilder.Entity("ServiceMarketplace.Entities.Service", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
